#!/bin/bash

C_RESET='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'

pre_commit_test_count=3
pre_commit_test_index=1

function run_test()
{
    local output exitcode
    printf "${C_YELLOW}[%s]${C_RESET} %-25s" "$pre_commit_test_index/$pre_commit_test_count" "$2"
    output=$(eval "$3" 2>&1)
    exitcode=$?

    if [[ $exitcode == 0 || $exitcode == 130 ]]; then
        echo -e "${C_GREEN}OK!${C_RESET}"
    else
        echo -e "${C_RED}NOK!${C_RESET}\n\n$output"
        exit 1
    fi

    $pre_commit_test_index="$(($pre_commit_test_index+1))"
}

modified_files="git diff --diff-filter=ACMR --name-only --cached | grep \".py$\""

run_test "mypy" "mypy src"
run_test "flake8" "flake8 src"
run_test "pytest" "pytest"
