name: Tests and Analysis
run-name: "Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}"

on:
  push:
  pull_request:
    branches:
      - main
env:
  PYTHON_LATEST: 3.9

jobs:
  test-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements_dev.txt
      - name: Static analysis (mypy)
        run: |
          mypy src --ignore-missing-imports
      - name: Static analysis (flake8)
        run: |
          flake8 src --max-line-length=120 --ignore=E203,W503,W293
      - name: Test
        run: |
          pytest -k 'not transactions'
